version: '2.1'

services:
  dev:
    image: node:carbon
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app

  install:
    extends:
      service: dev
    command: yarn install

  build:
    extends:
      service: dev
    command: yarn build

